#!/bin/bash

. /puppy/worker/sbin/functions

uid=$1

assert_valid_user $uid

if [ -e /etc/systemd/system/protected_u${uid}.esrvice ]; then
    /bin/systemctl stop protected_u${uid}.service 2>/dev/null
fi

exit 0
