#!/bin/bash

. /puppy/worker/sbin/functions

uid=$1

assert_valid_user $uid

if [ -e /var/log/puppy/apps/app_u${uid} ]; then
    /sbin/restorecon -R /var/log/puppy/apps/app_u${uid}
fi

if [ -e /var/cache/puppy/transitions/start_u${uid} ]; then
    /sbin/restorecon /var/cache/puppy/transitions/start_u${uid}
fi
