#!/bin/bash

for user in $(/usr/bin/sudo -u system /puppy/system/bin/policy_users $(/bin/hostname) || exit 1)
do
    /usr/bin/sudo -u system /puppy/system/bin/policy_ready $(/bin/hostname) $user || exit 1
done
