#!/bin/bash

# Generates a policy module for a user account on a Puppy machine and loads the
# module into the kernel.

# Import common functions for job shell programs.
. /puppy/worker/sbin/functions

# Assert that the arguments are valid.
#[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

#uid=$1

/bin/rm -rf /var/cache/puppy/policy/*

users=$(/usr/bin/sudo -u system /puppy/system/bin/policy_users $(/bin/hostname) || exit 1)
if [ ! -z "$users" ]
then
    echo "$users" | while read user
    do
        if [ $user -lt 20000 ]; then
            /puppy/worker/sbin/user_policy $user
        fi
    done
fi
