#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

dbid=$1

echo "CREATE DATABASE d$dbid" | /usr/bin/sudo -H -u postgres /puppy/janitor/bin/janitor_psql
