#!/bin/bash

. /puppy/worker/sbin/functions

uid=$1

assert_valid_user $uid

cat <<EOL > /etc/systemd/system/protected_u${uid}.service
[Unit]
Description=User supplied daemon for Puppy.
After=worker.service

[Service]
ExecStart=/usr/bin/sudo -H -u u${uid} /var/cache/puppy/transitions/start_u${uid}

[Install]
WantedBy=multi-user.target
EOL

cat <<EOL > /var/cache/puppy/transitions/start_u${uid}
#!/bin/bash

/bin/mkdir -p /home/u${uid}/log

cd /home/u${uid}/app
/home/u${uid}/bin/node /home/u${uid}/app/server.js 2>/home/u${uid}/log/stderr 1>/home/u${uid}/log/stdout
EOL

umask 077 
/bin/mkdir -p /var/log/puppy/apps/app_u${uid}
/bin/chmod 700 /var/log/puppy/apps/app_u${uid}
/bin/touch /var/log/puppy/apps/app_u${uid}/stderr
/bin/touch /var/log/puppy/apps/app_u${uid}/stdout

/bin/chmod 700 /var/cache/puppy/transitions/start_u${uid}

/bin/chown -R u${uid}:protected /var/log/puppy/apps/app_u${uid}
/bin/chown u${uid}:protected /var/cache/puppy/transitions/start_u${uid}

/bin/systemctl --system daemon-reload
