#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid
assert_valid_home_dir $uid

umask 022
/bin/mkdir -p /home/u$uid/.ssh
/bin/chmod 755 /home/u$uid/.ssh

umask 077
/bin/touch /home/u$uid/.ssh/authorized_keys
/bin/chmod 600 /home/u$uid/.ssh/authorized_keys

# If we redirect directly to authorized_keys, we'll have to modfiy the SELinux
# policy to allow the delegate domain to write home directories.
keys=$(/usr/bin/sudo -u system /puppy/system/bin/user_keys $(/bin/hostname) $uid || exit 1)

# Quoting keys is necessary to keep echo from swallowing the new lines.
# http://stackoverflow.com/questions/3445628/bash-line-concatenation-during-variable-interpolation
echo "$keys" > /home/u$uid/.ssh/authorized_keys
