#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid

/usr/bin/sudo -u system /puppy/system/bin/user_ready $(/bin/hostname) $uid || exit 1
