#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid

# Configure application directory.
address=$(/bin/cat /etc/puppy/address)

/bin/mkdir -p /home/u$uid/app
/bin/mkdir -p /home/u$uid/var
/bin/mkdir -p /home/u$uid/tmp
/bin/mkdir -p /home/u$uid/.puppy

config=$(/usr/bin/sudo -u system /puppy/system/bin/app_config $(/bin/hostname) $uid $address)
[ $? -eq 0 ] || exit 1

echo "$config" > /home/u$uid/app/configuration.json

# Configure MySQL.
config=$(/usr/bin/sudo -u system /puppy/system/bin/mysql_config $(/bin/hostname) $uid)
[ $? -eq 0 ] || exit 1
if [ ! -z "$config" ]
then
    umask 077
    echo "$config" > /home/u$uid/.puppy/pgpass
fi
