#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid

# Configure application directory.
address=$(/bin/cat /etc/puppy/address)

/bin/mkdir -p /home/u$uid/app
/bin/mkdir -p /home/u$uid/var
/bin/mkdir -p /home/u$uid/tmp

config=$(/usr/bin/sudo -u system /puppy/system/bin/app_config $(/bin/hostname) $uid $address)
[ $? -eq 0 ] || exit 1

echo "$config" > /home/u$uid/app/configuration.json

# Configure MySQL.
config=$(/usr/bin/sudo -u system /puppy/system/bin/mysql_config $(/bin/hostname) $uid)
[ $? -eq 0 ] || exit 1
umask 077
echo "$config" | while read line
do
    name=${line%% *}
    password=${line#* }
    /bin/rm -f /home/u$uid/.my.${name}.cnf
    echo "[client]" > /home/u${uid}/.my.${name}.cnf 
    echo "password=${password}" >> /home/u${uid}/.my.${name}.cnf 
done
