#!/bin/bash

. /puppy/bin/functions

uid=$1

assert_valid_user $uid

cat <<EOL > /etc/init/protected_u${uid}.conf
#!upstart

description "Puppy worker daemon u${uid}."
author "Alan Gutierrez"

start on runlevel [2345]
stop on runlevel [!2345]

script
    exec sudo -H -u u${uid} /var/cache/puppy/transitions/start_u${uid} 2>/var/log/puppy/apps/app_u${uid}/stderr 1>/var/log/puppy/apps/app_u${uid}/stdout
end script
EOL

cat <<EOL > /var/cache/puppy/transitions/start_u${uid}
#!/bin/bash

cd /home/u${uid}/app
exec /node/v0.2.6/bin/node /home/u${uid}/app/server.js
EOL

umask 077 
/bin/mkdir -p /var/log/puppy/apps/app_u${uid}
/bin/chmod 700 /var/log/puppy/apps/app_u${uid}
/bin/touch /var/log/puppy/apps/app_u${uid}/stderr
/bin/touch /var/log/puppy/apps/app_u${uid}/stdout

/bin/chmod 700 /var/cache/puppy/transitions/start_u${uid}

/bin/chown -R u${uid}:protected /var/log/puppy/apps/app_u${uid}
/bin/chown u${uid}:protected /var/cache/puppy/transitions/start_u${uid}
