#!/bin/bash

. /puppy/system/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid

/usr/bin/sudo -u private /puppy/private/bin/node_ready $(/bin/hostname) $uid
