#!/bin/bash

policies=$(
    for line in $(/usr/bin/sudo -u delegate /puppy/bin/machine_users $(/bin/hostname))
    do
        echo "/var/cache/puppy/policy/protected_u${line}.pp"
    done
)

echo "$policies" | /usr/bin/xargs -n 200 /usr/sbin/semodule -i
