#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid
assert_valid_home_dir $uid

gid=$(/bin/awk -F':' '$3 ~ /'$uid'/ { print $4 }'  /etc/passwd)

/bin/chown -R $uid:$gid /home/u$uid
