#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

user=$1
assert_valid_user $user

uid=$(($user + 10000))

if [ ! -d /home/u$uid ]; then
    abend "Home directory /home/u$uid does not exist."
fi

if [ $(/usr/bin/sudo -u delegate /puppy/bin/user_status $(/bin/hostname) $user) -ne 1 ]; then
    abend "User $uid has not been provisioned."
fi

umask 022
/bin/mkdir -p /home/u$uid/.ssh
/bin/chmod 755 /home/u$uid/.ssh

umask 077
/bin/touch /home/u$uid/.ssh/authorized_keys
/bin/chmod 600 /home/u$uid/.ssh/authorized_keys

# If we redirect directly to authorized_keys, we'll have to modfiy the SELinux
# policy to allow the delegate domain to write home directories.
keys=$(/usr/bin/sudo -u delegate /puppy/bin/user_keys $(/bin/hostname) $user)

# Quoting keys is necessary to keep echo from swallowing the new lines.
# http://stackoverflow.com/questions/3445628/bash-line-concatenation-during-variable-interpolation
echo "$keys" > /home/u$uid/.ssh/authorized_keys
