#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

user=$1
assert_valid_user $user
assert_valid_home_dir $user

uid=$(($user + 10000))

/sbin/restorecon -R "/home/u$uid"
