#!/bin/bash

. /puppy/worker/sbin/functions

[ $# -ne 2 ] && abend "Incorrect count of arguments ($#)."

uid=$1
group=$2
assert_valid_user $uid

echo $group | /bin/grep '^\(liminal\|protected\)$' > /dev/null || abend "Only liminal and protected groups allowed."

/usr/sbin/usermod -g $group u$uid 2>/dev/null || abend "Cannot modify user."
