#!/bin/bash

. /puppy/system/bin/functions

[ $# -lt 1 ] && abend "Incorrect count of arguments ($#)."

uid=$1
assert_valid_user $uid
assert_valid_home_dir $uid

gid=$(/bin/awk -F':' '$3 ~ /'$uid'/ { print $4 }'  /etc/passwd)

if [ $# -eq 1 ]; then
    /bin/chown -R $uid:$gid /home/u$uid
else
    shift
    while [ $# -gt 0 ]; do
        file=$(normalize_path /home/u$uid/$1)
        if [ $file == /home/u$uid ] || [[ $file == /home/u$uid/* ]]; then
            if [[ $file == */ ]]; then
                /bin/chown -R $uid:$gid $file
            else
                /bin/chown $uid:$gid $file
            fi
        else
            abend "Invalid home directory path $1."
        fi
        shift
    done
fi
