#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

user=$1
assert_valid_user $user

uid=$(($user + 10000))

/usr/sbin/semanage login -a -s protected_${uid}_u "u$uid"
