#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

user=$1
assert_valid_user $user

uid=$(($user + 10000))
existing=$(cut -d: -f1 /etc/passwd | grep '^u'$uid'$')
if [ $existing"x" == "x" ]; then
    /usr/sbin/useradd --gid 211 --uid $uid --home-dir "/home/u$uid" "u$uid" || abend "Unable to create user u$uid."
fi
