#!/bin/bash

. /puppy/bin/functions

[ $# -ne 1 ] && abend "Incorrect count of arguments ($#)."

user=$1
assert_valid_user $user

uid=$(($user + 10000))

if [ ! -d /home/u$uid ]; then
    abend "Home directory /home/u$uid does not exist."
fi

/usr/bin/sudo -u puppy /puppy/bin/user_status $(/bin/hostname) $user 
if [ $(/usr/bin/sudo -u puppy /puppy/bin/user_status $(/bin/hostname) $user) -ne 1 ]; then
    abend "User $uid has not been provisioned."
fi

umask 022
/bin/mkdir -p /home/u$uid/.ssh
/bin/chmod 755 /home/u$uid/.ssh

umask 077
/bin/touch /home/u$uid/.ssh/authorized_keys
/bin/chmod 600 /home/u$uid/.ssh/authorized_keys

/usr/bin/sudo -u puppy /puppy/bin/user_keys $(/bin/hostname) $user > /home/u$uid/.ssh/authorized_keys
